blog/urls.py
from django.conf.urls import url

from . import views

from django.conf import settings

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$',views.tags,name='tag'),
    url(r'^category/(?P<pk>[^/]+)/$',views.categoryn,name='categoryn'),
    url(r'^author/(?P<pk>[^/]+)/$',views.authors,name='author'),
    url(r'^search/$',views.search,name='search'),
    url(r'^test/$',views.test,name='test'),
    url(r'^contact/$',views.contact,name='contact')

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
#from DjangoUeditor.models import UEditorField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey,GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
STATUS_CHOICES = (
    ('d', '草稿'),
    ('p', '已发布'),
    ('w', '已撤回'),
)

@python_2_unicode_compatible
class Category(models.Model):
    """
    django 要求我们必须继承 models.Model 类，
    Category 只需要一个简单的分类名 name 就可以了。

    CharField 指定了 name 的数据类型，
    CharField 是字符型，
    max_length 指定其最大长度，
    超过这个长度的分类名就不能被存入数据库。

    当然 django 还为我们提供了各种各样的类型，
    如日期时间类型 DateTimeField、
    整数类型 IntegerField 等等。
    django 内置的类型全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100,unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '类别'
        verbose_name_plural = '类别集'

@python_2_unicode_compatible
class Tag(models.Model):
    """
    标签 Tag 也比较简单，
    和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=20,unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签集'


@python_2_unicode_compatible
class ViewNum(models.Model):
    content_type=models.ForeignKey(ContentType)
    object_id=models.PositiveIntegerField()
    content_object=GenericForeignKey()

    view_nums = models.PositiveIntegerField(default=0)

    def __str__(self):
        return '<%s:%s> %s' % (self.content_object,self.object_id,self.view_nums)


@python_2_unicode_compatible
class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField('标题',max_length=70,unique=True)

    # 文章正文，我们使用了 TextField。
    # 比较短的字符串存储可以使用 CharField，
    # 但对于文章的正文来说可能会是一大段文本，
    # 因此使用 TextField 来存储大段文本。
    #body = models.TextField()
    #body=UEditorField(u'内容',width=600, height=300, toolbars="mini", imagePath="%(year)s/%(month)s/%(day)s/%(basename)s.%(extname)s")
    body = RichTextUploadingField(u'内容', config_name='awesome_ckeditor')
    # 这两个列分表表示了文章的创建时间和最后一次修改时间，
    # 存储时间的列用 DateTimeField。
    created_time = models.DateTimeField('发表时间',auto_now_add=True)
    modified_time = models.DateTimeField('更新时间',auto_now=True,null=True)

    # 文章摘要，可以没有文章摘要，
    # 但默认情况下 CharField 要求我们必须存入数据，
    # 否则就会报错。
    # 指定 blank=True 后就可以允许空值了。
    excerpt = models.CharField('摘要',max_length=200, blank=True)
    status = models.CharField('状态',max_length=1, choices=STATUS_CHOICES,default='d')
    #('d', 'Draft'), ('p', 'Published'), ('w', 'Withdrawn')
    # 这是分类与标签，
    # 分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类与标签对应的表关联起来，
    # 但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，
    # 但是一个分类下可以有很多篇文章，
    # 所以我们使用的是 ForeignKey，
    # 即一对多的关系。
    # 而对于标签来说，
    # 一篇文章可以有多个标签，
    # 同一个标签下也可能有多篇文章，
    # 所以我们使用 ManyToManyField，
    # 表明这是多对多的关系。
    # 同时我们规定文章可以没有标签，
    # 因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，
    # 请看教程中的解释，
    # 亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category,verbose_name='类别',blank=True,null=True)
    tags = models.ManyToManyField(Tag, verbose_name='标签',blank=True)

    # 文章作者
    # 这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，
    # 专门用于处理网站用户的注册、登录等流程，
    # User 是 django 为我们已经写好的用户模型，
    # 这里我们通过 ForeignKey 把文章和 User 关联起来，
    # 因为我们规定一篇文章只能有一个作者，
    # 而一个作者可能会写多篇文章，
    # 因此这是一对多的关系，
    # 和 Category 类似。
    author = models.ForeignKey(User,verbose_name='作者',blank=True, null=True)
    #author = models.OneToOneField(User)
    #read_num = models.PositiveIntegerField('阅读量',default=0)
    view_num = GenericRelation(ViewNum)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk':self.pk})

    class Meta:
        ordering = [ '-created_time']
        verbose_name='文章'
        verbose_name_plural='文集'

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Post,Category,ViewNum,Tag
from django.contrib.auth.models import User
from .paginator import getPages
from django.contrib.contenttypes.models import ContentType
from django.db.models import Count,Q

#import markdown
# Create your views here.
WHICHTEMPLATE= False

def index(request):

    post_list = Post.objects.filter(status='p')
    if request.user.is_authenticated:
        post_list=Post.objects.filter(Q(author=request.user)|Q(status='p'))

    #post_list=Post.objects.annotate(Count('view_num'))#只是取到对象，不能取到对象对应的字段
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages

    if WHICHTEMPLATE :
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)

def detail(request,pk):
    #post = get_object_or_404(Post,pk=pk,status='p')
    if request.user.is_authenticated:
        post = get_object_or_404(Post,Q(author=request.user)|Q(status='p'),pk=pk)
    else:
        post = get_object_or_404(Post, pk=pk, status='p')
    strs = 'post_%s_readed'% pk

    obj_type = ContentType.objects.get_for_model(Post)
    v = ViewNum.objects.get_or_create(content_type=obj_type,object_id=post.id)
    if strs not in request.COOKIES:
        v[0].view_nums+=1
        v[0].save()

    if request.user.is_authenticated:
    #previous blog
        pre_post=Post.objects.filter(Q(author=request.user)|Q(status='p'),id__lt=pk).order_by('-id')
        if pre_post.exists():
            pre_post=pre_post[0]
        else:
            pre_post={}

        next_post=Post.objects.filter(Q(author=request.user)|Q(status='p'),id__gt=pk).order_by('id')
        if next_post.exists():
            next_post=next_post[0]
        else:
            next_post={}
    else:
        pre_post = Post.objects.filter(status='p',id__lt=pk).order_by('-id')
        if pre_post.exists():
            pre_post = pre_post[0]
        else:
            pre_post = {}

        next_post = Post.objects.filter(status='p',id__gt=pk)
        if next_post.exists():
            next_post = next_post[0]
        else:
            next_post = {}

    data = {}
    """
    if request.user.is_authenticated:
        data['change']=True
    else:
        data['change']=False
    """
    #data['user']=request.user
    data['post']=post
    data['pre_post']=pre_post
    data['next_post']=next_post
    #data['view_num']=v[0]

    if WHICHTEMPLATE  :

        response = render(request,'blog/detail.html',data)
    else:
        response = render(request, 'blog/detail2.html', data)

    response.set_cookie( strs,True)
    return response

def archives(request,year,month):
    post_list = Post.objects.filter(status='p',created_time__year=year,created_time__month=month)
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages

    if WHICHTEMPLATE :
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)
    #return render(request, 'blog/index.html', data )

def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    post_list = Post.objects.filter(category=cate,status='p')
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages

    if WHICHTEMPLATE:
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)
    #return render(request, 'blog/index.html', data )

def tags(request,pk):
    cate = get_object_or_404(Tag,pk=pk)
    post_list = Post.objects.filter(tags=cate,status='p')
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages

    if WHICHTEMPLATE :
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)
    #return render(request, 'blog/index.html', data )

def categoryn(request,pk):
    cate = get_object_or_404(Category,name=pk)
    post_list = Post.objects.filter(category=cate,status='p')
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages

    if WHICHTEMPLATE :
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)
    #return render(request, 'blog/index.html', data )

def authors(request,pk):
    author = get_object_or_404(User,username=pk)
    post_list = Post.objects.filter(author=author,status='p')
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages

    if WHICHTEMPLATE :
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)

def search(request):
    str=request.GET['search']
    post_list = Post.objects.filter(Q(title__icontains=str,status='p')|Q(body__contains=str,status='p'))
    data = {}
    pages, post_list = getPages(request,post_list)

    data['post_list'] = post_list
    data['pages'] = pages
    data['search']=str

    if WHICHTEMPLATE :
        return render(request, 'blog/index.html', data )
    else:
        return render(request, 'blog/index2.html', data)

def test(request):
    values = request.META.items()
    #values.sort()
    html=[]
    for k,v in values:
        html.append('<tr><td>%s<td><td>%s<td></tr>' % (k,v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))


def contact(request):
    data={}
    data['allpostnum']= Post.objects.filter(status='p').count()
    return render(request,'blog/contact.html',data)

templates/blog/base.html
<!DOCTYPE html>
{% load blog_tags %}
<html>
	<head>
		<title>SummerDawn</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta property="wb:webmaster" content="a75ae64e33d7a2d6" />
		{% load staticfiles %}
	    <!-- css -->

		<link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
		<link rel="stylesheet" href="http://cdn.bootcss.com/ionicons/2.0.1/css/ionicons.min.css">
		<link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
	    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
		<link rel="stylesheet" href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/github.css' %}">
		<link rel="stylesheet" href="{% static 'blog/css/special.css' %}" type="text/css" >

        <!--link rel="stylesheet" href="{% static 'blog/css/prettify.css' %}"-->


	    <!-- js -->
	    <script src="http://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
		<script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	    <script src="{% static 'blog/js/pace.min.js' %}"></script>
	    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
		<script src="{% static 'blog/js/sucaijiayuan.js' %}"></script>

	</head>

	<body>
		<div class="container">
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="{% url 'blog:index' %}"><b>SUMMER·DAWN</b></a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11 "><a href="{% url 'admin:index' %}blog/post/add" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="{% url 'admin:index' %}blog/post/" data-hover="Admin">Admin</a></li>
									<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="About">About</a> </li>
								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="{% url 'blog:search' %} ">
									<input type="search" placeholder="Search" required name="search">
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>


		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-8">

						{% block main %}
                        {% endblock main %}

						{% block jiathis %}
						{% endblock jiathis %}

						{% block post_pre_next %}
						{% endblock post_pre_next %}

						{% block paginations %}
						{% endblock paginations %}

						{% block uyan %}
						{% endblock uyan %}

						{% block other %}
						{% endblock other %}

					</main>
					<aside class="col-md-4">
						<div class="widget widget-recent-posts">
							<h3 class="widget-title">最新文章</h3>
							{% get_recent_posts as recent_post_list %}
							<ul>
								{% for post in recent_post_list %}
								<li>
									<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
								</li>
								{% endfor %}
							</ul>
						</div>
						<div class="widget widget-archives">
							<h3 class="widget-title">归档</h3>
							{% archives as date_list %}
							<ul>
								{% for date in date_list %}
								<li>
									<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年 {{ date.month }} 月</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div class="widget widget-category">
							<h3 class="widget-title">分类</h3>
							{% get_categories as category_list %}
							<ul>
								{% for category in category_list %}
								<li>
									<a href="{% url 'blog:category' category.pk %}">{{ category.name }}({{category.num_posts}})</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div class="widget ">
							<h3 class="widget-title">标签云</h3>
							{% get_tags as tag_list %}

								{% for tag in tag_list %}

									<a class="label label-default"  href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}({{tag.num_posts}})</a>

								{% endfor %}

						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; SummerDawn·Since 2017·<a href="http://www.summerdawn.top/" target="_blank" title="邂逅夏日黎明">夏日黎明</a>
						{% if user.is_authenticated %}
                        {% block loginnext %}

                        {% endblock loginnext %}
                        {% else %}
                        <a href="{%url 'admin:login' %}?next={%url 'blog:index' %}">·请登录</a>
                        {% endif %}
						</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="Home">Home</a></li>
    				<li class="cl-effect-11 "><a href="{% url 'admin:index' %}blog/post/add" data-hover="Blog">Blog</a></li>
    				<li class="cl-effect-11"><a href="{% url 'admin:index' %}blog/post/" data-hover="Admin">Admin</a></li>
					<li class="cl-effect-11"><a href="{% url 'blog:contact' %}" data-hover="About">About</a> </li>
				</ul>
			</nav>
		</div>
		<script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>
		<script>hljs.initHighlightingOnLoad();</script>
		<script src="//cdn.bootcss.com/highlightjs-line-numbers.js/1.1.0/highlightjs-line-numbers.min.js"></script>
		<script>hljs.initLineNumbersOnLoad();</script>
		<script src="{% static 'blog/js/script.js' %}"></script>
		<script src="https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"></script>


	{% block extra_footer %}
	{% endblock extra_footer %}
	<div style="display: none;" id="rocket-to-top">
	<div style="opacity:0;display: block;" class="level-2"></div>
	<div class="level-3"></div>
	</div>
	</body>
</html>

templates/blog/contact.html
{% extends 'blog/base2.html' %}
{% load static %}
{% load blog_tags %}
               {% block header %}

                <header class="intro-header" style="background-image:url({% static 'blog/img/home-bg.jpg' %})">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                                <div class="site-heading">
                                    <h1 class="hidden-xs">SUMMER·DAWN</h1>
                                    <h2 class="visible-xs">SUMMER·DAWN</h2>
                                    <hr class="small">
                                    <p class="lead">如果需要，那就现在开始<br>
                                        如果开始，请从这里出发<br><br>
                                        ——记录自由而真实的人生</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </header>
               {% endblock header %}
{% block main %}
    <div class="container">
        <div class="row">
                <div class="col-lg-5 col-lg-offset-2 col-md-6 col-md-offset-1">
                        <h3 >联系我们</h3>
                        <div id="phone">
                        <address>
                          <p><strong>深圳市众海科技有限公司</strong><br>
                                    观光路3009号<br>
                                    光明新区，深圳<br>
                          <abbr title="Phone">PH:</abbr> (0755) 23198385</p>

                            <p><strong>联系人</strong><br>
                                刘林海
                          <a href="mailto:#">liulinhai@outlook.com</a></p>
                        </address>

                            <p><strong>使用说明 </strong><br>
                            本网站实行邀请注册，欢迎加入我们！<br>请将意向账户名发至上述邮箱；获得账户后，即可撰文评论，网站操作参<a href="{% url 'blog:detail' 36 %}">SummerDawn网站使用说明</a></p>
                        </div>



						<div >
							<h3>最新文章</h3>
							{% get_recent_posts as recent_post_list %}
                            <ol>
                            {% for post in recent_post_list %}
                            <li><span class="badge" style="float:right;margin-right: 50px;">新</span>
                            <a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:18 }}</a>
                            </li>
                            {% endfor %}
                            </ol>
                            本站已有公开文章 {{ allpostnum }} 篇。
						</div>
                </div>
                    <aside class="col-md-3">
						<div >
							<h3 >归档</h3>
							{% archives as date_list %}
							<ul>
								{% for date in date_list %}
								<li>
									<a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }}年 {{ date.month }} 月</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div >
							<h3 >分类</h3>
							{% get_categories as category_list %}
							<ul>
								{% for category in category_list %}
								<li>
									<a href="{% url 'blog:category' category.pk %}">{{ category.name }}({{category.num_posts}})</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div >
							<h3 >标签云</h3>
							{% get_tags as tag_list %}

								{% for tag in tag_list %}

									<a class="label label-default"  href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}({{tag.num_posts}})</a>

								{% endfor %}

						</div>
					</aside>
            </div>
        </div>

{% endblock main %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block main %}
						{% for post in post_list %}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="{% url 'blog:category' post.category.pk|default:0 %}">{{ post.category.name }} </a></span>
			
									<span class="post-date"><a href="{% url 'blog:archives' post.created_time.year post.created_time.month %}"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
			
									<span class="post-author"><a href="{% url 'blog:author' post.author %}">{{ post.author }}</a></span>
                                    <span >阅读({% get_view_num  post.id  %})</span>
                                    <br>
                                    <span>
                                    {% for tag in post.tags.all %}
                                      <a title="访问该标签下所有文章" href="{% url 'blog:tag' tag.pk %}" class="label label-default">{{ tag.name }}</a>
                                    {% empty %}
                                    暂无标签！
                                    {% endfor %}
                                    </span>
                    </p>

								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{post.excerpt|default:post.body|striptags|safe|truncatechars:100}}</p>
								<div class="read-more cl-effect-14">
									<a href="{{ post.get_absolute_url }}" class="more-link">继续阅读<span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						{% empty %}
						<div class="no-post">暂时还没有发布文章！</div>
						{% endfor %}
{% endblock main %}

{% block paginations %}
	{% if pages.num_pages > 1 %}
	<div style="text-align:center">
        <ul class="pagination">
    {# 上一页，这里需要用到has_previous方法判断是否有上一页 #}
    <li>
        {% if post_list.has_previous %}
            <a href="?page={{ post_list.previous_page_number }}" aria-label="Previous">
            {% else %}
            <a href="?page={{ post_list.number }} " aria-label="Previous">
            {% endif %}

            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>

    {# 遍历所有页码 #}
    {% for page in pages.page_range %}
        <li><a href="?page={{ page }}">{{ page }}</a></li>
    {% endfor %}

    {# 下一页，这里需要用到has_next方法判断是否有下一页 #}
    <li>
        {% if post_list.has_next %}
        <a href="?page={{ post_list.next_page_number }}" aria-label="Next">
            {% else %}
         <a href="?page={{ post_list.number}}" aria-label="Next">
            {% endif %}

            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
</ul>
        <p> 共{{ pages.count }}篇博文·当前第{{ post_list.number }}页/共{{ pages.num_pages }}页</p>
    </div>




{% block extra_footer %}
    {#设置凸显当前的页码#}
    <script type="text/javascript">
        $(".pagination li:eq({{ post_list.number}})").addClass("active");
    </script>
{% endblock %}

{% endif %}
{% endblock paginations %}

    {% block loginnext %}
    ·已登录 by <a title="退出登录" href="{%url 'admin:logout' %}?next={%url 'blog:index' %}">{{user.get_username}}</a>
    {% endblock loginnext %}

templates/blog/index2.html
{% extends 'blog/base2.html' %}
{% load blog_tags %}
{% load static %}

               {% block header %}

<header class="intro-header" style="background-image:url({% static 'blog/img/home-bg.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>SUMMER·DAWN</h1>
                    <hr class="small">
                    <p class="lead">
                        如果需要，那就现在开始<br>
                        如果开始，请从这里出发<br><br>
                        ——记录自由而真实的人生
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
               {% endblock header %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            {% for post in post_list %}
            <div class="post-preview">
                <a href="{{ post.get_absolute_url }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{post.excerpt|default:post.body|striptags|safe|truncatechars:120}}
                    </h3>
                </a>
                <p class="post-meta">
                    <a href="{% url 'blog:author' post.author %}">{{ post.author }}</a> · {{ post.created_time|timesince}}前
                    <span><i class="fa fa-eye" aria-hidden="true"></i> {% get_view_num  post.id  %} </span>
                    <span><i class="fa fa-comments" aria-hidden="true"></i> {% get_comment_num  post.id  %} </span>
                    <br>{% if post.category.pk %}<i class="fa fa-folder-o"></i> <a href="{% url 'blog:category' post.category.pk %} ">{{post.category.name}}</a>
                    &nbsp; {%endif %}
                    {% if post.tags.all %}
                    <i class="fa fa-tags"></i>
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blog:tag' tag.pk %}" class="label label-default">{{ tag.name }}</a>
                    {% empty %}
                    暂无标签！
                    {% endfor %}
                    {%endif %}
                </p>
            </div>
            <hr>


            {% empty %}
            <div class="post-preview">暂时还没有发布文章！</div>
            {% endfor %}

            <!-- Pager -->
            <ul class="pager">
                {% if post_list.has_previous %}
                <li class="previous">
                    <a href="?page={{ post_list.previous_page_number }}">  &larr; Newer Posts </a>
                </li>
                {% endif %}

                {% if post_list.has_next %}
                <li class="next">
                    <a href="?page={{ post_list.next_page_number }}">Older Posts &rarr;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock main %}

                         {% block loginnext %}
                        ·已登录 by {{user.get_username}} ·<a title="退出登录" href="{%url 'admin:logout' %}?next={%url 'blog:index' %}"><i class="fa fa-sign-out fa-border " aria-hidden="true">登出</i></a>
                         {% endblock loginnext %}

templates/blog/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>